### ISSUE TITLE
'<DEFAULT>' string in FIBO Time Machine

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/html-pages#120]
We need to replace '<DEFAULT>' string in FIBO Time Machine with a more appropriate string, e.g., stable.

**Comment by rosolowski** [comment]
@mereolog the change has been applied in https://github.com/edmcouncil/html-pages/commit/7441eafe71d8a014d673f9e4245d7996b6797a2d

**Comment by dasawanaka** [comment]
> @mereolog the change has been applied in [7441eaf](https://github.com/edmcouncil/html-pages/commit/7441eafe71d8a014d673f9e4245d7996b6797a2d)

make PR
