### ISSUE TITLE
Orphaned Pages

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/html-pages#123]
[Products.vue](https://github.com/edmcouncil/html-pages/blob/develop/fibo/src/views/Products.vue) and other pages are orphaned, i.e., they cannot be reached from the landing pages.

All these pages need to found, reviewed, and relinked or removed.

**Comment by dasawanaka** [comment]
`products.vue` are disabled because the products download is moved to another location, the file apparently has not been deleted, Can I delete all unlinked files or do I need to leave some of them?

**Comment by mereolog** [comment]
> `products.vue` are disabled because the products download is moved to another location, the file apparently has not been deleted, Can I delete all unlinked files or do I need to leave some of them?

I think we can link this page to 'FIBO Products' item in FIBO "burger":
![image](https://user-images.githubusercontent.com/11171688/152795919-81befdf0-7386-4fc5-99da-b19f410753ac.png)

**Comment by dasawanaka** [comment]
> I think we can link this page to 'FIBO Products' item in FIBO "burger

Ok, I will change it so that it directs to the corrected page with links to EDMConnectTM, which is where the ontology download is now, Those links were to download ontologies directly from the website.
