### ISSUE TITLE
Stylling of `Browse FIBO domains`

### ISSUE THREAD

**Issue by dasawanaka** [edmcouncil/html-pages#175]
The section with `Select FIBO version` in the content looks similar to the section with `Browse FIBO domains`, but the second does not have a frame. Should it perhaps be the same?

![image](https://user-images.githubusercontent.com/26776168/161036868-909eaf3d-81c1-4d78-9010-d9646188a5f5.png)

In mobile version of `html-pages` both have this frame:
![image](https://user-images.githubusercontent.com/26776168/161037097-92670bdb-829d-42de-b870-413e1aa6e183.png)

**Comment by rosolowski** [comment]
I think the reason for it was that the frame/shadow boxes mean active elements (dropdowns, search, expands) which user can interact with. "Empty" boxes with no frame are just title for the section.
If we were to add the frame to desktop version of "Browse FIBO domains" maybe we should add option to collapse it, like on mobile but default to expanded state.
