### ISSUE TITLE
Dependabot alerts - Prototype Pollution in minimist

### ISSUE THREAD

**Issue by dasawanaka** [edmcouncil/html-pages#178]
We do not have 'minimist' directly in the dependencies.
Should update the following packages that contain it:

- [ ] @vue/cli-service
- [ ] @vue/cli-plugin-eslint 
- [ ] @vue/eslint-config-airbnb

Is likely to return a problem with  [issuecomment-1046656161](https://github.com/edmcouncil/html-pages/pull/132#issuecomment-1046656161), backport to an older version fixes this problem, When dependencies are updated, cooperation with @mereolog will be required to check for compatibility in IOS system with docker.

**Comment by mereolog** [comment]
> We do not have 'minimist' directly in the dependencies. Should update the following packages that contain it:
> 
> * [ ]  @vue/cli-service
> * [ ]  @vue/cli-plugin-eslint
> * [ ]  @vue/eslint-config-airbnb
> 
> Is likely to return a problem with [issuecomment-1046656161](https://github.com/edmcouncil/html-pages/pull/132#issuecomment-1046656161), backport to an older version fixes this problem, When dependencies are updated, cooperation with @mereolog will be required to check for compatibility in IOS system with docker.

Yes, please do update them.
