### ISSUE TITLE
New maturity levels

### ISSUE THREAD

**Issue by dasawanaka** [edmcouncil/html-pages#202]
### New maturity levels

As long as there are no new icons, `provisonal` and `informative` are treated the same (old dev type):
- PROVISIONAL("https://spec.edmcouncil.org/fibo/ontology/FND/Utilities/AnnotationVocabulary/Provisional", "Provisional")
- INFORMATIVE("https://spec.edmcouncil.org/fibo/ontology/FND/Utilities/AnnotationVocabulary/Informative", "Informative")

prod is now type with label `Release`
RELEASE("https://spec.edmcouncil.org/fibo/ontology/FND/Utilities/AnnotationVocabulary/Release", "Release")

Warnings on website should display only for `provisonal` and `informative` (`release`, `not_set` and `mixed` should be ignored)
![image](https://user-images.githubusercontent.com/26776168/171382345-aa2e70d7-f08d-4d5f-8cee-d3f65db8163c.png)

- MIXED("https://spec.edmcouncil.org/ontoviewer/Mixed", "Mixed")
- NOT_SET("https://spec.edmcouncil.org/ontoviewer/NotSet", "Not Set")

there is no longer an icon in the json response

```
"maturityLevel": {
			"label": "NOT_SET",
			"iri": "https://spec.edmcouncil.org/ontoviewer/NotSet"
		},
```

### For now, it should be:

- release 
![image](https://user-images.githubusercontent.com/26776168/171382982-68bb8882-b4a9-4969-a771-7539c3ef6de2.png)
- provisional  
![image](https://user-images.githubusercontent.com/26776168/171383263-9178986b-93a9-4e19-a687-a8825ac5883c.png)
- informative 
![image](https://user-images.githubusercontent.com/26776168/171383297-989765d7-3619-4c2c-9d8b-112ebfb68e3c.png)
- mixed 
![image](https://user-images.githubusercontent.com/26776168/171383608-379379bc-9444-497a-acba-bfbd17697e6d.png)
- not_set - nothing 

All information based on: [PR-240(OV)](https://github.com/edmcouncil/onto-viewer/pull/240)

  @mereolog do you accept this solution?

**Comment by mereolog** [comment]
For now this may work, but let us wait for the opinions of other contributors.
