### ISSUE TITLE
Problem with documentation of strapi-configuration-for-develop-local-run

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/html-pages#340]
I experienced the following problem with documentation in https://github.com/edmcouncil/html-pages/blob/develop/general/README.md#strapi-configuration-for-develop-local-run.

```
$ cd onto-viewer-web
$ npm install

up to date, audited 11 packages in 840ms

found 0 vulnerabilities

$ npm run dev
npm ERR! Missing script: "dev"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
```

**Comment by dasawanaka** [comment]
I didint find any problems. Strapi and frontend in nuxt has separate scripts, and its all is written in this documentation, 
strapi has own scripts for run: 
`npm run develop`
and frontend in nuxt 
`npm run dev`

You linked paragraph with strapi configuration, strapi has script on 
`npm run develop`
and its clearly declared in doc in appropriate section.

**Comment by dasawanaka** [comment]
You must execute this script from within the forlder where the package.json file is located.
