### ISSUE TITLE
Vue application installation failure

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/html-pages#85]
Following instructions on https://github.com/edmcouncil/html-pages#running-the-content-of-website-locally fails to start yarn server.

After the following setup on a MS Windows Server 2016 machine:
1. node.js version 16.3.0 installed from https://nodejs.org/en/
2. yarn installed via `npm install --global yarn (got me 1.22.10 version)
I tried to run yarn in D:\projects\fibo\git\edmc\html-pages\fibo - this resulted in this error:
```
error D:\projects\fibo\git\edmc\html-pages\fibo\node_modules\node-sass: Command failed.
....
gyp verb check python checking for Python executable "c:\python27\python.exe" in the PATH
gyp verb `which` failed Error: not found: c:\python27\python.exe
gyp verb `which` failed     at getNotFoundError (D:\projects\fibo\git\edmc\html-pages\fibo\node_modules\which\which.js:13:12)
```
After installing python 2.7.18 and setting the path to the folder with python 2.7. the same error occurs.
One probably needs to run
`npm config set python c:\python27\python.exe`
 as per https://stackoverflow.com/a/64486670 - this solve the previous error but 'discovers' a new one:
```
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".

Build FAILED.

  MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".

    0 Warning(s)
    1 Error(s)
```
I got similar issues on a MS W10 machine and different, but also critical, on a MacOs system.

**Comment by trypuz** [comment]
@kbalcerek, could you help, please?

**Comment by Karpas** [comment]
>   MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".

Have you tried to update Windows Build Tools?
`
npm install --global windows-build-tools
npm config set msvs_version 2017 --global
`


> I got similar issues on a MS W10 machine and different, but also critical, on a MacOs system.

@mereolog  please paste what error you receive on MacOS.

**Comment by przemekgradzki** [comment]
@mereolog what do you think about [#running-the-content-of-website-locally](https://github.com/edmcouncil/html-pages#running-the-content-of-website-locally) based on [Docker-Compose](https://medium.com/bb-tutorials-and-thoughts/vue-js-local-development-with-docker-compose-275304534f7c)?

**Comment by mereolog** [comment]
@przemekgradzki if this is a quick job, we may go for it.

**Comment by przemekgradzki** [comment]
@mereolog see  #86 and  [FIBO-235](https://jira.makolab.net/browse/FIBO-235)
